name: deploy
on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Orderbook image metadata
        id: meta_orderbook
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-orderbook
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Orderbook image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.orderbook
          push: true
          tags: ${{ steps.meta_orderbook.outputs.tags }}
          labels: ${{ steps.meta_orderbooko.outputs.labels }}

      - name: Migration image metadata
        id: meta_migration
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-migration
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Migration image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/gpv2/Dockerfile.migration
          push: true
          tags: ${{ steps.meta_migration.outputs.tags }}
          labels: ${{ steps.meta_migration.outputs.labels }}

